"""
Horizontal FOV measurement helper - entirely generated by Claude.

Opens a webcam at a specified resolution with overlays that make the frame
edges and optical centre unambiguous, so the wall-marking procedure is
accurate. Run on a PC with the webcam attached.

    python3 fov_measure.py                        # 640x360 MJPG, device 0
    python3 fov_measure.py --width 1920 --height 1080
    python3 fov_measure.py --device 1
    python3 fov_measure.py --list                 # probe device indices

Once you have the two wall marks:

    python3 fov_measure.py --compute --distance 1.50 --width-measured 2.55

Procedure
---------
1. Camera square-on to a flat wall. Perpendicular optical axis. Being off
   square is the dominant error source -- equalize the distance from the
   lens to the wall at both left and right frame edges.
2. Measure d, the perpendicular distance from the FRONT OF THE LENS to the
   wall. A metre or two works well.
3. Slide a marker along the wall until it sits exactly on the LEFT edge
   line in the preview. Mark the wall.
4. Repeat for the RIGHT edge line. Mark.
5. Measure w between the two marks.
6. Run with --compute.

Keys
----
q / ESC   quit
"""

import argparse
import math
import sys

import cv2


def list_devices(max_index=8):
    print("Probing device indices...\n")
    found = []
    for i in range(max_index):
        cap = cv2.VideoCapture(i)
        if cap.isOpened():
            ret, frame = cap.read()
            if ret:
                h, w = frame.shape[:2]
                print(f"  index {i}: opened, default frame {w}x{h}")
                found.append(i)
            else:
                print(f"  index {i}: opened but no frame")
            cap.release()
    if not found:
        print("  nothing found -- check the camera is plugged in")
    print()
    return found


def compute_fov(distance, width_measured):
    """
    FOV_h = 2 * arctan(w / 2d)

    distance        d, perpendicular lens-to-wall distance
    width_measured  w, distance on the wall between the two edge marks

    Both in the same units; the ratio is what matters.
    """
    return math.degrees(2.0 * math.atan(width_measured / (2.0 * distance)))


def vertical_fov(fov_h_deg, frame_w, frame_h):
    """Vertical FOV implied by horizontal FOV and aspect, square pixels."""
    half_h = math.radians(fov_h_deg) / 2.0
    half_v = math.atan(math.tan(half_h) * (frame_h / frame_w))
    return math.degrees(2.0 * half_v)


def preview(device, req_w, req_h, fourcc):
    cap = cv2.VideoCapture(device, cv2.CAP_V4L2)
    if not cap.isOpened():
        print(f"Could not open device {device}. Try --list.")
        return

    if fourcc:
        cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*fourcc))
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, req_w)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, req_h)

    ret, frame = cap.read()
    if not ret:
        print("Camera opened but returned no frame.")
        cap.release()
        return

    h, w = frame.shape[:2]

    print(f"Requested : {req_w}x{req_h}")
    print(f"Actual    : {w}x{h}")
    if (w, h) != (req_w, req_h):
        print("  NOTE: driver did not honour the request. The actual size")
        print("  above is what you are measuring -- record it.")
    print("\nMark the wall at the two magenta edge lines. Press q to quit.\n")

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Edge markers. Inset by 1px so they are actually visible rather
        # than half-clipped at the boundary.
        cv2.line(frame, (1, 0), (1, h), (255, 0, 255), 2)
        cv2.line(frame, (w - 2, 0), (w - 2, h), (255, 0, 255), 2)

        # Centre crosshair -- use this to square the camera to the wall.
        cx, cy = w // 2, h // 2
        cv2.line(frame, (cx, cy - 20), (cx, cy + 20), (0, 255, 255), 1)
        cv2.line(frame, (cx - 20, cy), (cx + 20, cy), (0, 255, 255), 1)

        # Quarter gridlines, useful for checking the view is symmetric
        # about the centre (i.e. that you are actually square-on).
        for frac in (0.25, 0.75):
            x = int(w * frac)
            cv2.line(frame, (x, 0), (x, h), (80, 80, 80), 1)

        cv2.putText(frame, f"{w}x{h}", (8, 24),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
        cv2.putText(frame, "mark wall at magenta lines", (8, h - 12),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

        cv2.imshow("FOV measurement", frame)
        if cv2.waitKey(1) & 0xFF in (ord('q'), 27):
            break

    cap.release()
    cv2.destroyAllWindows()


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--device", default=0)
    p.add_argument("--width", type=int, default=640)
    p.add_argument("--height", type=int, default=360)
    p.add_argument("--fourcc", default="MJPG",
                   help="four character code, or empty string for driver default")
    p.add_argument("--list", action="store_true",
                   help="probe device indices and exit")
    p.add_argument("--compute", action="store_true",
                   help="compute FOV from measurements and exit")
    p.add_argument("--distance", type=float,
                   help="d, perpendicular lens-to-wall distance")
    p.add_argument("--width-measured", type=float, dest="width_measured",
                   help="w, distance on the wall between the two edge marks")
    args = p.parse_args()

    if args.list:
        list_devices()
        return

    if args.compute:
        if args.distance is None or args.width_measured is None:
            print("--compute needs both --distance and --width-measured")
            sys.exit(1)

        fov_h = compute_fov(args.distance, args.width_measured)
        fov_v = vertical_fov(fov_h, args.width, args.height)

        print(f"\n  d = {args.distance}")
        print(f"  w = {args.width_measured}")
        print(f"\n  FOV_h = {fov_h:.2f} deg")
        print(f"  FOV_v = {fov_v:.2f} deg   (implied at {args.width}x{args.height})")
        print(f"\n  deg per pixel, horizontal: {fov_h / args.width:.4f}")

        if not 50.0 <= fov_h <= 100.0:
            print("\n  WARNING: outside the plausible range for a webcam.")
            print("  Most likely the camera was not square to the wall, or")
            print("  d was measured from the wrong reference point.")

        print(f"\n  -> set FOV_H_DEG = {fov_h:.2f} in tracker.py\n")
        return

    fourcc = args.fourcc if args.fourcc else None
    device = int(args.device) if str(args.device).isdigit() else args.device
    preview(device, args.width, args.height, fourcc)


if __name__ == "__main__":
    main()
